//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covoiturage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class covoiturageEntities : DbContext
    {
        public covoiturageEntities()
            : base("name=covoiturageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conversation> conversations { get; set; }
        public virtual DbSet<evaluation> evaluations { get; set; }
        public virtual DbSet<marque> marques { get; set; }
        public virtual DbSet<modele> modeles { get; set; }
        public virtual DbSet<pay> pays { get; set; }
        public virtual DbSet<reservation> reservations { get; set; }
        public virtual DbSet<trajet> trajets { get; set; }
        public virtual DbSet<utilisateur> utilisateurs { get; set; }
        public virtual DbSet<ville> villes { get; set; }
        public virtual DbSet<voiture> voitures { get; set; }
    }
}
