//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covoiturage
{
    using System;
    using System.Collections.Generic;
    
    public partial class trajet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trajet()
        {
            this.evaluations = new HashSet<evaluation>();
            this.reservations = new HashSet<reservation>();
        }
    
        public int idtrajet { get; set; }
        public Nullable<System.DateTime> datecreation { get; set; }
        public Nullable<System.DateTime> datelimiteinscription { get; set; }
        public Nullable<int> idVilleDepart { get; set; }
        public Nullable<int> idVilleArrivee { get; set; }
        public string pointDepart { get; set; }
        public string pointArrivee { get; set; }
        public Nullable<System.DateTime> datedepart { get; set; }
        public Nullable<System.TimeSpan> heuredepart { get; set; }
        public Nullable<System.TimeSpan> heurearrivee { get; set; }
        public Nullable<int> nbplaces { get; set; }
        public Nullable<decimal> prix { get; set; }
        public string remarque { get; set; }
        public Nullable<bool> Autoroute { get; set; }
        public Nullable<bool> fumeur { get; set; }
        public Nullable<bool> musique { get; set; }
        public Nullable<bool> annimaux { get; set; }
        public Nullable<bool> complet { get; set; }
        public string immatriculation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evaluation> evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual ville ville { get; set; }
        public virtual ville ville1 { get; set; }
        public virtual voiture voiture { get; set; }
    }
}
