//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covoiturage
{
    using System;
    using System.Collections.Generic;
    
    public partial class voiture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voiture()
        {
            this.trajets = new HashSet<trajet>();
        }
    
        public string immatriculation { get; set; }
        public string couleur { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> idModele { get; set; }
        public Nullable<int> idUtilisateur { get; set; }
    
        public virtual modele modele { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trajet> trajets { get; set; }
        public virtual utilisateur utilisateur { get; set; }
    }
}
